version: '3.8'

services:
  app:
    build: ./ # This would use the Dockerfile in the current directory to build the image
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    restart: unless-stopped