apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsn-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bsn-api
  template:
    metadata:
      labels:
        app: bsn-api
    spec:
      containers:
        - name: bsn-api
          image: lukasvdgaag/bsn-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 300Mi
              cpu: "0.1"
