apiVersion: v1
kind: Service
metadata:
  name: bsn-api-service
  namespace: default
spec:
  selector:
    app: bsn-api
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
  type: LoadBalancer